adding neo to tixlfinance
tixlfinance/tixlfinance-community-data pull request #126
Opened 2021-01-26 15:31 UTC by Mrxdaunknown

hopefully everything is working fine^^

2021-01-26 16:35 UTC, PrinceMatthew commented
Hi @Mrxdaunknown, I have recently contributed to the project and as far as I can tell, your PR looks fine to me. However, if you'd like to, you may add a description for the coin in a separate file named description.md. For examples, you can take a look at Litecoin. Anyways, a dev will approve the PR ASAP, after obviously reviewing it.

2021-01-26 16:46 UTC, Mrxdaunknown commented
Hi PrinceMatthew, thanks for your advice. Maybe I´ll add that later to the Project.

2021-01-28 16:25 UTC, fnnhnsn requested changes

2021-01-28 16:25 UTC, fnnhnsn commented on projects/neo-NEO/info.json
> +  "category_tags": ["smart_contract_platform"],
Hey @Mrxdaunknown, unfortunately we do not have a smart contract platform category yet. You can check all existing categories in the `categories` directory next to the `projects` directory. However, you can still keep this tag for now and maybe also add the category as well.

2021-01-28 16:25 UTC, fnnhnsn commented on projects/neo-NEO/info.json
> +      "handle": "Neo Smart Economy"
Hey @Mrxdaunknown unfortunately due to the youtube formatting, the youtube handle has to be the same as the channel id, so in this case `UCl1AwEDN0w5lTmfJEMsY5Vw`. Could you maybe adjust that as well? Thanks a lot! :)

2021-01-28 16:25 UTC, fnnhnsn commented
Hey @Mrxdaunknown, sorry for the late review. There are just two minor things that you could double check again, afterwards I'll merge your pr. Thanks a lot for your contribution!

2021-01-28 17:52 UTC, Mrxdaunknown commented on projects/neo-NEO/info.json
> +      "handle": "Neo Smart Economy"
Roger that :). So instead of "Neo Smart Economy" it would be UCl1AwEDN0w5lTmfJEMsY5Vw? Okay.

2021-01-28 18:00 UTC, Mrxdaunknown commented on projects/neo-NEO/info.json
> +  "category_tags": ["smart_contract_platform"],
Okay thanks, will go with NFT then :). Later we can add smart_contract_platform as a tag for NEO. Maybe I´ll see if we can add it as a category.

2021-02-02 09:44 UTC, fnnhnsn approved these changes
Hey @Mrxdaunknown, thanks a lot, I'll merge it!

2021-02-02 09:51 UTC, merged